In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [3]:
data = pd.read_excel(r'E:\DS\tezendra\Projects\Job Simulation of Common Wealth\Task 3\commonwealth_bank_social_media_dataset.xlsx')
data.describe()

       Commonwealth Bank Social Media Dataset
count                                       8
unique                                      8
top                                   Purpose
freq                                        1

In [4]:
total_length = len(data)
total_length

8

In [5]:
missing_values = data.isnull().sum()
missing_values

Commonwealth Bank Social Media Dataset    0
dtype: int64

In [6]:
df_cleaned = data.dropna()
df_cleaned

              Commonwealth Bank Social Media Dataset
0                                            Purpose
1  This simulated dataset supports Task 3 of the ...
2                                     Important note
3  All posts and metrics in this workbook are fic...
4                            How learners can use it
5  Use the Social_Media_Posts sheet to explore se...
6                                 Suggested analyses
7  1. Identify the topics that appear most often....