In [ ]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn.impute import KNNImputer

ImportError: cannot import name 'knnimpute' from 'sklearn.preprocessing' (c:\Users\thapa\anaconda3\Lib\site-packages\sklearn\preprocessing\__init__.py)

In [3]:
df_customers = pd.read_csv(r"E:\DS\tezendra\Projects\Marketing Analysis\Customer Behavior & Sales 2020–2026\customers.csv")
df_orders = pd.read_csv(r"E:\DS\tezendra\Projects\Marketing Analysis\Customer Behavior & Sales 2020–2026\orders.csv")

In [4]:
df_customers.head()

,customer_id,country,age,gender,membership_tier,registration_date,total_orders,total_spend_usd,avg_order_value_usd,days_since_last_purchase,preferred_category,preferred_device,preferred_payment_method,acquisition_channel,reviews_given,avg_review_score,returns_made,wishlist_items,newsletter_subscribed,churned
0,C00001,United States,40,Male,Free,2019-01-17,4,286.63,63.78,49,Food & Grocery,Mobile,Debit Card,Social Media,1,4.5,0,12,0,0
1,C00002,United States,20,Female,Free,2026-03-04,11,1245.18,107.32,126,Toys & Games,Mobile,Debit Card,Organic Search,2,2.6,1,1,0,0
2,C00003,United States,43,Female,Gold,2026-02-08,4,195.37,42.74,0,Home & Kitchen,Mobile,PayPal,Referral,0,4.8,0,0,1,0
3,C00004,United States,41,Male,Free,2025-03-19,6,99.45,15.61,6,Electronics,Desktop,PayPal,Organic Search,2,4.2,0,8,1,0
4,C00005,France,37,Other,Platinum,2024-09-10,36,2593.21,79.09,161,Clothing & Apparel,Tablet,Debit Card,Social Media,9,4.0,4,5,1,0

In [5]:
np.sort(df_customers["preferred_category"].unique())

array(['Automotive', 'Beauty & Personal Care', 'Books',
       'Clothing & Apparel', 'Electronics', 'Food & Grocery',
       'Health & Wellness', 'Home & Kitchen', 'Jewelry & Accessories',
       'Office Supplies', 'Pet Supplies', 'Sports & Outdoors',
       'Toys & Games', 'Travel & Luggage'], dtype=object)

In [6]:
np.sort(df_orders["category"].unique())

array(['Automotive', 'Beauty & Personal Care', 'Books',
       'Clothing & Apparel', 'Electronics', 'Food & Grocery',
       'Health & Wellness', 'Home & Kitchen', 'Jewelry & Accessories',
       'Office Supplies', 'Pet Supplies', 'Sports & Outdoors',
       'Toys & Games', 'Travel & Luggage'], dtype=object)

In [7]:
df_customers["preferred_payment_method"].unique()

array(['Debit Card', 'PayPal', 'UPI / Digital Wallet', 'Credit Card',
       'Bank Transfer', 'Cryptocurrency', 'Buy Now Pay Later'],
      dtype=object)

In [8]:
df_orders.head()

,order_id,customer_id,order_date,year,month,quarter,day_of_week,product_name,category,unit_price_usd,...,payment_method,device_used,delivery_days,delivery_date,order_status,returned,customer_rating,session_duration_minutes,pages_viewed_before_purchase,is_repeat_customer
0,O000001,C07108,2020-08-27,2020,8,Q3,Thursday,Tire Inflator,Automotive,62.91,...,Credit Card,Desktop,3,2020-08-30,Delivered,0,NaN,14.4,1,1
1,O000002,C03487,2024-04-11,2024,4,Q2,Thursday,Stud Earrings Gold,Jewelry & Accessories,18.44,...,Credit Card,Mobile,2,2024-04-13,Delivered,0,NaN,9.0,4,0
2,O000003,C03062,2023-06-25,2023,6,Q2,Sunday,Pen Set Premium,Office Supplies,109.79,...,PayPal,Desktop,3,2023-06-28,Delivered,0,4.0,3.2,17,0
3,O000004,C00888,2020-08-16,2020,8,Q3,Sunday,Smart Watch Series 5,Electronics,87.21,...,Credit Card,Tablet,2,2020-08-18,Returned,1,NaN,32.2,3,1
4,O000005,C01674,2020-04-24,2020,4,Q2,Friday,Stud Earrings Gold,Jewelry & Accessories,94.30,...,Debit Card,Mobile,5,2020-04-29,Delivered,0,2.8,54.7,2,1

In [9]:
df_customers.describe()

,age,total_orders,total_spend_usd,avg_order_value_usd,days_since_last_purchase,reviews_given,avg_review_score,returns_made,wishlist_items,newsletter_subscribed,churned
count,8000.000000,8000.000000,8000.000000,8000.000000,8000.000000,8000.000000,8000.000000,8000.000000,8000.000000,8000.000000,8000.000000
mean,35.616375,16.545250,1558.642350,94.845566,59.583875,3.228750,4.109112,0.849500,4.457125,0.617375,0.089375
std,11.170455,14.681064,2284.094953,78.992885,60.610355,3.942698,0.523992,1.407337,4.854391,0.486058,0.285302
min,18.000000,1.000000,4.890000,5.000000,0.000000,0.000000,1.800000,0.000000,0.000000,0.000000,0.000000
25%,27.000000,5.000000,336.055000,44.690000,16.000000,0.000000,3.800000,0.000000,1.000000,0.000000,0.000000
50%,35.000000,12.000000,845.700000,72.270000,41.000000,2.000000,4.200000,0.000000,3.000000,1.000000,0.000000
75%,43.000000,23.000000,1892.165000,118.560000,84.000000,5.000000,4.500000,1.000000,6.000000,1.000000,0.000000
max,75.000000,79.000000,61282.480000,1051.730000,582.000000,28.000000,5.000000,11.000000,41.000000,1.000000,1.000000

In [10]:
df_orders.describe()

,year,month,unit_price_usd,quantity,subtotal_usd,discount_pct,discount_amount_usd,shipping_fee_usd,tax_pct,tax_amount_usd,total_amount_usd,delivery_days,returned,customer_rating,session_duration_minutes,pages_viewed_before_purchase,is_repeat_customer
count,25000.000000,25000.000000,25000.000000,25000.000000,25000.000000,25000.000000,25000.000000,25000.000000,25000.000000,25000.000000,25000.000000,25000.000000,25000.000000,9251.000000,25000.000000,25000.00000,25000.000000
mean,2022.652840,6.352280,68.124030,1.695520,116.187322,5.630000,6.345500,3.867579,10.677080,11.746785,125.456186,4.179480,0.080800,4.002324,16.780432,6.51256,0.645960
std,1.814996,3.514614,57.258933,1.045436,136.994998,9.740785,17.530764,3.269618,6.504922,17.723056,145.635016,2.548507,0.272533,0.577576,15.811830,5.26557,0.478231
min,2020.000000,1.000000,3.360000,1.000000,3.360000,0.000000,0.000000,0.000000,0.000000,0.000000,3.000000,1.000000,0.000000,1.500000,0.300000,1.00000,0.000000
25%,2021.000000,3.000000,29.250000,1.000000,38.467500,0.000000,0.000000,0.000000,8.000000,2.300000,43.450000,3.000000,0.000000,3.600000,7.100000,2.00000,0.000000
50%,2023.000000,6.000000,51.530000,1.000000,72.390000,0.000000,0.000000,3.990000,10.000000,6.220000,78.775000,4.000000,0.000000,4.100000,12.100000,5.00000,1.000000
75%,2024.000000,9.000000,87.877500,2.000000,140.160000,10.000000,5.250000,6.990000,18.000000,13.990000,149.872500,5.000000,0.000000,4.400000,21.100000,9.00000,1.000000
max,2026.000000,12.000000,697.030000,5.000000,2636.450000,50.000000,421.580000,9.990000,20.000000,303.990000,2730.880000,14.000000,1.000000,5.000000,361.200000,24.00000,1.000000

In [11]:
df_customers.isnull().sum()

customer_id                 0
country                     0
age                         0
gender                      0
membership_tier             0
registration_date           0
total_orders                0
total_spend_usd             0
avg_order_value_usd         0
days_since_last_purchase    0
preferred_category          0
preferred_device            0
preferred_payment_method    0
acquisition_channel         0
reviews_given               0
avg_review_score            0
returns_made                0
wishlist_items              0
newsletter_subscribed       0
churned                     0
dtype: int64

In [16]:
df_orders.isnull().sum()

order_id                            0
customer_id                         0
order_date                          0
year                                0
month                               0
quarter                             0
day_of_week                         0
product_name                        0
category                            0
unit_price_usd                      0
quantity                            0
subtotal_usd                        0
discount_pct                        0
discount_amount_usd                 0
shipping_fee_usd                    0
tax_pct                             0
tax_amount_usd                      0
total_amount_usd                    0
payment_method                      0
device_used                         0
delivery_days                       0
delivery_date                       0
order_status                        0
returned                            0
customer_rating                 15749
session_duration_minutes            0
pages_viewed_before_purchase        0
is_repeat_customer                  0
dtype: int64

In [19]:
df_orders['customer_rating'].describe()

count    9251.000000
mean        4.002324
std         0.577576
min         1.500000
25%         3.600000
50%         4.100000
75%         4.400000
max         5.000000
Name: customer_rating, dtype: float64